CREATE TABLE questions
(
    _id INT IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author INT FOREIGN KEY REFERENCES users,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BIT NOT NULL DEFAULT 0,
    tags VARCHAR(300) NOT NULL DEFAULT ''
);